### ISSUE TITLE
How to send a notify

### ISSUE THREAD

**Issue by Hermanverschooten** [mtrudel/hap#1]
Hi,
I am very impressed with your HAP library.
I added it to an existing nerves project and I can turn on/off my light with my iPhone. Nice!
But I also have another way to turn on the light.
I would like to reflect the current state of the light in my Home app.
Can you tell me how I can do this?
eg, If I turn on the light using `put_value` from the console, do I then need to send something, somewhere, somehow?

Thanks

**Comment by mtrudel** [comment]
Thanks for the good feedback!

Being able to write back state to HomeKit requires support for HomeKit events within HAP. This is actually a fairly big workup as it requires some non-standard changes to the underlying HTTP lib to support the sending of async server events. It's on the books for HAP 2.0 but likely not for a while (PRs are of course welcome however!). 

In the meantime, HAP really only supports changes sent from a HomeKit controller to the device in question. In practice, I've been able to work reliably with the light bulb, window covering & header / cooler service types where changes are made in the iOS UI & it stays up-to-date with the actual state of the devices. Anything beyond this (ie: cases where the device needs to inform a HomeKit controller that it has changed in some way) is going to be mostly non-functional until 2.0 comes along.

**Comment by mtrudel** [comment]
Closing the issue as there's nothing more to be done here. If you have any further issues please don't hesitate to open a new one!

**Comment by mtrudel** [comment]
Update for @Hermanverschooten: I figured out how to land event support in a not-too-difficult way that also answers a couple of long-standing questions I've had with the lower level libraries used by HAP (thousand_island and bandit). I'm working through the changes required in the underlying libraries with a goal of landing event support in HAP in the near future (by 'near-future' I mean sometime in Q2-Q3 2021). Stay tuned!

**Comment by mtrudel** [comment]
@Hermanverschooten, I just released HAP 0.4.0 which fully supports notifications. Documentation for using them can be found on the `HAP.ValueStore` module at https://hexdocs.pm/hap/HAP.ValueStore.html. 

This is *extremely* new functionality so if you encounter any issues I would very much love to hear about / fix them!

**Comment by Hermanverschooten** [comment]
So far I have added the `set_change_token\2` and added a `value_changed/0` function to my implementation. And called it manually after changing my GPIO pin, and it works like a charm.

**Comment by mtrudel** [comment]
Glad to hear it!
