### ISSUE TITLE
Suppress Bandit logging?

### ISSUE THREAD

**Issue by Hermanverschooten** [mtrudel/hap#152]
Is there a way to suppress or change the logging level for the started Bandit instance?
Home access kit is quite chatty, with several dozen `GET /characteristics` flashing over my screen and overflowing my `RingLogger`.
It would be great if we could suppress these.

**Comment by mtrudel** [comment]
It's [this line](https://github.com/mtrudel/hap/blob/main/lib/hap/http_server.ex#L7). I agree that it's a bit spammy; maybe we should remove it entirely?

**Comment by mtrudel** [comment]
Added in 0.6.0, just released
