### ISSUE TITLE
Outlet service receiving `0`, `1`, `false` for its `:on` characteristic

### ISSUE THREAD

**Issue by hez** [mtrudel/hap#40]
The Outlet service has a required [`on` characteristic](https://github.com/mtrudel/hap/blob/d1067b6f6b3b0c0135f9dfa77555afd6c8d1bd52/lib/hap/characteristics/on.ex) which is labelled as type `bool`.

## Issue

In my testing it received all of these values, `0` `1` `false` to the `put_value/2` on my accessory.

## Reproducing

I have a simple implementation of an outlet which [here](https://github.com/hez/hdmi_hap_accessory/tree/feature/on-charactistic-example)

Steps

1. exlixir install, mix deps.get, mix compile, etc
2. Run with `CEC_ADDRESS=0 iex -S mix`
3. Add the accessory to your Home
4. Turning on and off the outlet from Home app, will call `put_value(0 | 1, :on)`
5. Create an automation where the outlet will automaticly turn off after some time (1min!) and `put_value(false, :on)` will be called.

**Comment by hez** [comment]
To get around this I ended up implementing `put_value/2` for 0,1,false, and true.

https://github.com/hez/hdmi_hap_accessory/blob/feature/on-charactistic-example/lib/hdmi_hap_accessory/hap/outlet.ex#L22-L38

**Comment by mtrudel** [comment]
Per table 6.5 in HAP R2 a bool is allowed to be any of those. We should probably cast the values to an actual boolean though. I'll whip that up tomorrow.

**Comment by hez** [comment]
oh no! I didn't realize that! yeah a cast down to an actual `boolean` would be preferable in Elixir. Casting it might break backwards compatibility though 😬 I can imagine people out there having coded for `1` / `0` because thats what Homekit was sending them....

**Comment by mtrudel** [comment]
> oh no! I didn't realize that! yeah a cast down to an actual `boolean` would be preferable in Elixir. Casting it might break backwards compatibility though 😬 I can imagine people out there having coded for `1` / `0` because thats what Homekit was sending them....

HAP is 0.x.y for a reason :). I do t feel bad about breaking compatibility for the zero other users at the moment lol

**Comment by petermm** [comment]
if distant memory serves me right, I remember handling this issue where Home.app would send one set of bools and "Eve for HomeKit".app another set of bools..

so normalizing bools would be great for dev ergonomics!

**Comment by mtrudel** [comment]
Done in `main`. Please to confirm it works and I'll cut a release!

**Comment by hez** [comment]
Tested with my outlet

✅ true / false received when controlling from Home app
✅ false received via auto turn off

Looks good!

**Comment by hez** [comment]
Would it be helpful to add some documentation about what characteristic values can be?  Having gone through the discovery process the last little while I could put up a PR with ones I have tested.

**Comment by mtrudel** [comment]
Yeah sounds great! In the meantime I'll close this issue as it's been fixed adhoc in `main`.

**Comment by mtrudel** [comment]
0.4.7 just released with this and all previous changes!

**Comment by hez** [comment]
Thank you!
